# vals = [ ('Phone', 'Invincibility', '1-999-724-654-5537'),
#     ('Phone', 'Max Health & Armor', '1-999-887-853'),
#     ('Phone', 'Recharge Special Ability', '1-999-769-3787'),
#     ('Phone', 'Super Jump', '1-999-467-8648'),
#     ('Phone', 'Run Faster', '1-999-228-8463'),
#     ('Phone', 'Swim Faster', '1-999-468-44557'),
#     ('Phone', 'Skyfall', '1-999-759-3255'),
#     ('Phone', 'Slow Motion Aim', '1-999-332-3393'),
#     ('Phone', 'Moon Gravity', '1-999-356-2837'),
#     ('Phone', 'Drunk Mode', '1-999-547-861'),
#     ('Phone', 'Explosive Melee Attacks', '1-999-4684-2637'),
#     ('Phone', 'Explosive Ammo Rounds', '1-999-444-439'),
#     ('Phone', 'Flaming Ammo Rounds', '1-999-462-363-4279'),
#     ('Phone', 'Give Parachute', '1-999-759-3483'),
#     ('Phone', 'Change Weather', '1-999-625-348-7246'),
#     ('Phone', 'Slippery Cars', '1-999-766-9329'),
#     ('Phone', 'Spawn Buzzard Attack Helicopter', '1-999-289-9633'),
#     ('Phone', 'Spawn Stunt Plane', '1-999-2276-78676'),
#     ('Phone', 'Spawn Duster', '1-999-359-77729'),
#     ('Phone', 'Spawn Comet', '1-999-266-38'),
#     ('Phone', 'Spawn Rapid GT', '1-999-727-4348'),
#     ('Phone', 'Spawn PCJ-600 Motorcycle', '1-999-762-538'),
#     ('Phone', 'Spawn Sanchez Dirt Bike', '1-999-633-7623'),
#     ('Phone', 'Spawn Trashmaster', '1-999-872-433'),
#     ('Phone', 'Spawn Stretch Limo', '1-999-846-39663'),
#     ('Phone', 'Spawn BMX Bike', '1-999-226-348'),
#     ('Vehicle', 'Spawn Buzzard Attack Helicopter', 'BUZZOFF'),
#     ('Vehicle', 'Spawn Stunt Plane', 'BARNSTORM'),
#     ('Vehicle', 'Spawn Duster', 'FLYSPRAY'),
#     ('Vehicle', 'Spawn Comet', 'COMET'),
#     ('Vehicle', 'Spawn Rapid GT', 'RAPIDGT'),
#     ('Vehicle', 'Spawn PCJ-600 Motorcycle', 'ROCKET'),
#     ('Vehicle', 'Spawn Sanchez Dirt Bike', 'OFFROAD'),
#     ('Vehicle', 'Spawn Trashmaster', 'TRASHED'),
#     ('Vehicle', 'Spawn Stretch Limo', 'VINEWOOD'),
#     ('Vehicle', 'Spawn BMX Bike', 'BANDIT'),
#     ('Player Ability', 'Invincibility (5 min)', 'PAINKILLER'),
#     ('Player Ability', 'Max Health & Armor', 'TURTLE'),
#     ('Player Ability', 'Recharge Special Ability', 'POWERUP'),
#     ('Player Ability', 'Super Jump', 'HOPTOIT'),
#     ('Player Ability', 'Run Faster', 'CATCHME'),
#     ('Player Ability', 'Swim Faster', 'GOTGILLS'),
#     ('Player Ability', 'Skyfall', 'SKYFALL'),
#     ('Player Ability', 'Slow Motion Aim', 'DEADEYE'),
#     ('Player Ability', 'Moon Gravity', 'FLOATER'),
#     ('Player Ability', 'Drunk Mode', 'LIQUOR'),
#     ('Player Ability', 'Explosive Melee Attacks', 'HOTHANDS'),
#     ('Player Ability', 'Explosive Ammo Rounds', 'HIGHEX'),
#     ('Player Ability', 'Flaming Ammo Rounds', 'INCENDIARY'),
#     ('Player Ability', 'Give Parachute', 'SKYDIVE'),
#     ('Player Ability', 'Change Weather', 'MAKEITRAIN'),
#     ('Player Ability', 'Slippery Cars', 'SNOWDAY'),]

# for i, val in enumerate(vals):
#     print(f"INSERT INTO individual_tasks VALUES ({i}, '{val[0]}', '{val[1]}', '{val[2]}', 3);")


# cheat_codes = [
#     ('Character', 'Stan Lee', '7HWU4L'),
#     ('Character', 'Arnim Zola', 'N7KQ4T'),
#     ('Character', 'Beetle', 'KXFQ87'),
#     ('Character', 'Black Cat', 'P9OWL0'),
#     ('Character', 'Black Panther', 'J58RSS'),
#     ('Character', 'Blob', 'P8SEL9'),
#     ('Character', 'Carnage', 'AA0Z50'),
#     ('Character', 'Chase Stein', 'Q5E42T'),
#     ('Character', 'Curt Connors', 'S94766'),
#     ('Character', 'Darkstar', 'S94766'),
#     ('Character', 'Demolition Man', 'D5B7O3'),
#     ('Character', 'Diamond Girl', '3ZDB2W'),
#     ('Character', 'Fandral', 'XTIY22'),
#     ('Character', 'Green Goblin', 'V3ZZFN'),
#     ('Character', 'Hawkeye', 'AA0Z50'),
#     ('Character', 'Howard the Duck', '2NGSRZ'),
#     ('Character', 'Iron Man (Hulkbuster)', 'CK7SDS'),
#     ('Character', 'Loki', '5T3CQU'),
#     ('Character', 'Odin', 'ODIN'),
#     ('Character', 'Polaris', 'B7AA3K'),
#     ('Character', 'Red Hulk', '4U9M8Z'),
#     ('Character', 'Ronan the Accuser', 'QMGLE'),
#     ('Character', 'Squirrel Girl', 'CC9H39'),
#     ('Character', 'Thanos', '8HG9HC'),
#     ('Character', 'Thor', 'UUDDLRLRBA'),
#     ('Vehicle', 'Deadpool\'s Scooter', 'G6RE7P'),
#     ('Vehicle', 'Hydra Tank (Marvel)', '8W8K2P'),
#     ('Vehicle', 'Spider Bike (Marvel)', 'SH9MZQ'),
#     ('Vehicle', 'Stark Jet (Marvel)', 'B7AA3K')
# ]

# for i, cheat_codes in enumerate(cheat_codes):
#     print(f"INSERT INTO individual_tasks VALUES ({i+52}, '{cheat_codes[0]}', '{cheat_codes[1]}', '{cheat_codes[2]}', 1);")

# cheat_codes = [
#     ('Character', 'Alfred', 'ZAQ637'),
#     ('Character', 'Batgirl', 'JKR331'),
#     ('Character', 'Bruce Wayne', 'BDJ327'),
#     ('Character', 'Catwoman (Classic)', 'M1AAWW'),
#     ('Character', 'Clown Goon', 'HJK327'),
#     ('Character', 'Commissioner Gordon', 'DDP967'),
#     ('Character', 'Fishmonger', 'HGY748'),
#     ('Character', 'Freeze Girl', 'XVK541'),
#     ('Character', 'Freeze Henchman', 'NJL412'),
#     ('Character', 'The Joker (Tropical)', 'CCB199'),
#     ('Character', 'Joker Goon', 'UTF782'),
#     ('Character', 'Joker Henchman', 'YUN924'),
#     ('Character', 'LexBot', 'W49CSJ'),
#     ('Character', 'Mad Hatter', 'JCA283'),
#     ('Character', 'Man-Bat', 'NYU942'),
#     ('Character', 'Military Policeman', 'MKL382'),
#     ('Character', 'Nightwing', 'MVY759'),
#     ('Character', 'Penguin Goon', 'BJH782'),
#     ('Character', 'Penguin Henchman', 'NKA238'),
#     ('Character', 'Penguin Minion', 'KJP748'),
#     ('Character', 'Policeman', 'PLB946'),
#     ('Character', 'Poison Ivy Goon', 'GTB899'),
#     ('Character', 'Police Marksman', 'HKG984'),
#     ('Character', 'Riddler Goon', 'CRY928'),
#     ('Character', 'Riddler Henchman', 'XEU824'),
#     ('Character', 'Riddler\'s Girlfriend', 'XWP645'),
#     ('Character', 'S.W.A.T.', 'HTF114'),
#     ('Character', 'Two-Face Goon', 'EER929'),
#     ('Character', 'Two-Face Henchman', 'MMN786'),
#     ('Character', 'Ventriloquist', 'KJK327'),
#     ('Vehicle', 'Bat-Tank', 'KNTT4B'),
#     ('Vehicle', 'Bruce Wayne\'s Private Jet', 'LEA664'),
#     ('Vehicle', 'Catwoman\'s Motorcycle', 'HPL826'),
#     ('Vehicle', 'Garbage Truck', 'DUS483'),
#     ('Vehicle', 'Goon Helicopter', 'GCH328'),
#     ('Vehicle', 'Harley Quinn\'s Hammer Truck', 'RDT637'),
#     ('Vehicle', 'Mad Hatter\'s Glider', 'HS000W'),
#     ('Vehicle', 'Mad Hatter\'s Steamboat', 'M4DM4N'),
#     ('Vehicle', 'Penguin Submarine', 'BTN248'),
#     ('Vehicle', 'Police Bike', 'LJP234'),
#     ('Vehicle', 'Police Boat', 'PLC999'),
#     ('Vehicle', 'Police Car', 'KJL832'),
#     ('Vehicle', 'Police Helicopter', 'CWR732'),
#     ('Vehicle', 'Police Van', 'MAC788'),
#     ('Vehicle', 'Riddler\'s Jet', 'HAHAHA'),
#     ('Vehicle', 'The Joker\'s Van', 'JUK657'),
#     ('Extra', 'Disguise (Detective)', 'BWQ458'),
#     ('Extra', 'Fast Build', 'KLJ584'),
#     ('Extra', 'Fast Grapple', 'RM4PR8'),
#     ('Extra', 'Flaming Batarangs', 'JRBDCB'),
#     ('Extra', 'Immune to Freeze', 'JXUDY6'),
#     ('Extra', 'Invincibility', 'WYD5CP'),
#     ('Extra', 'More Batarang Targets', 'XWP645'),
#     ('Extra', 'Regenerate Hearts', 'HJH7HJ')
# ]

cheat_codes = [
    ('Health and Stamina', '"You flourish before you die"', 'Refills health, stamina, and dead eye bars'),
    ('Weapons and Ammo', '"Abundance is the dullest desire"', 'Grants infinite ammo supply'),
    ('Weapons and Ammo', '"Greed is American virtue"', 'Adds Pump-Action Shotgun, Bolt Action Rifle, Mauser Pistol, and Semi-Automatic Pistol'),
    ('Horses', '"My kingdom is a horse"', 'Increases your horse\'s bonding level'),
    ('Money and Items', '"Share"', 'Grants a set of basic weapons'),
    ('Money and Items', '"Greed is now a virtue"', 'Adds $500 to your in-game funds'),
    ('Dead Eye', '"Guide me better"', 'Allows for manual targeting in Dead Eye'),
    ('Miscellaneous', '"A simple life, a beautiful death"', 'Spawns a cart'),
    ('Miscellaneous', '"Keep your dreams simple"', 'Spawns a race horse'),
    ('Miscellaneous', '"You want punishment"', 'Increases your wanted level'),
    ('Miscellaneous', '"You want freedom"', 'Decreases your wanted level')
]

for i, cheat_codes in enumerate(cheat_codes):
    print(f"INSERT INTO individual_tasks VALUES ({i+135}, '{cheat_codes[0]}', '{cheat_codes[1]}', '{cheat_codes[2]}', 4);")